[build]
  functions = "functions"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/:version/static/:resource"
  to = "/api/:version/static/:resource.json"
  status = 200
  force = true

[[redirects]]
  from = "/api/:version/:resource/*"
  to = "/.netlify/functions/:resource/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/configure/:hash"
  to = "/configure/?hash=:hash"
  status = 200
  force = true

[[redirects]]
  from = "/feed/:hash"
  to = "/.netlify/functions/feeds/:hash"
  status = 200

[[redirects]]
  from = "/welcome/:hash"
  to = "/welcome/?hash=:hash"
  status = 200
  force = true
