[build]
  functions = "functions"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/:version/:resource/*"
  to = "/.netlify/functions/:resource/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/feed/:hash"
  to = "/.netlify/functions/feeds/:hash"
  status = 200
